"""empty message

Revision ID: 6acd8d693342
Revises: be0c77cb6d00
Create Date: 2020-06-22 11:25:22.135293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6acd8d693342'
down_revision = 'be0c77cb6d00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('merck_equiv', sa.String(length=2048, collation='utf8_general_ci'), nullable=True))
    op.drop_index('IDX_products', table_name='products')
    op.drop_index('IDX_products_model', table_name='products')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('IDX_products_model', 'products', ['model'], unique=False)
    op.create_index('IDX_products', 'products', ['chemical_name', 'model'], unique=False)
    op.drop_column('products', 'merck_equiv')
    # ### end Alembic commands ###
