"""Initial migration.

Revision ID: be0c77cb6d00
Revises: 
Create Date: 2020-06-16 16:30:57.781337

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'be0c77cb6d00'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('msds', sa.String(length=2048, collation='utf8_general_ci'), nullable=True))
    op.add_column('products', sa.Column('tds', sa.String(length=2048, collation='utf8_general_ci'), nullable=True))
    op.drop_index('chemical_name_2', table_name='products')
    op.drop_index('name_2', table_name='products')
    op.drop_column('products', 'documentation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('documentation', mysql.VARCHAR(length=2048), nullable=True))
    op.create_index('name_2', 'products', ['name', 'model'], unique=False)
    op.create_index('chemical_name_2', 'products', ['chemical_name', 'model'], unique=False)
    op.drop_column('products', 'tds')
    op.drop_column('products', 'msds')
    # ### end Alembic commands ###
